get:
  tags:
    - Product
  summary: Get the list of products
  description: Get the list of the available products
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/product_list.yaml'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '../../components/responses/Problem.yaml'