get:
  tags:
    - Product
  summary: Get the list of products
  description: Get the list of the available products
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/product_list.yaml'
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '../../components/responses/Problem.yaml'
post:
  tags:
    - Product
  summary: Create a new product
  description: Create a new product
  operationId: createProduct
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/v1/product.yaml
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product.yaml
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '../../components/responses/Problem.yaml'