openapi: 3.0.3
info:
  title: API First with Spring Boot
  description: "This is a sample open API spec to learn how to create an open API specification"
  termsOfService: http://swagger.io/terms/
  contact:
    email: pshameed99@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
servers:
  - url: https://example.com/api/v1
tags:
  - name: Customer
    description: Operations about customer management
  - name: Product
    description: Operations about product management
  - name: Order
    description: Operations about order management
paths:
  /v1/customers:
      $ref: paths/v1/customers.yaml
  /v1/customers/{customerId}:
    $ref: paths/v1/customers_{customerId}.yaml
  /v1/products:
    $ref: paths/v1/products.yaml
  /v1/products/{productId}:
    $ref: paths/v1/products_{productId}.yaml
  /v1/orders:
    $ref: paths/v1/orders.yaml
  /v1/orders/{orderId}:
    $ref: paths/v1/orders_{orderId}.yaml


security:
  - basic_auth: []
components:
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header